pipeline {
     agent any
     stages {
          stage("Docker build") {
               steps {
                    sh "docker build -t <username>/book-library ."
               }
          }

          stage("Docker login") {
               steps {
                    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'docker-hub-credentials',
                               usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
                         sh "docker login --username $USERNAME --password $PASSWORD"
                    }
               }
          }

          stage("Docker push") {
               steps {
                    sh "docker push <username>/book-library"
               }
          }

          stage("Deploy to staging") {
               steps {
                    sh "docker run -d --rm -p 8080:8080 --name book-library <username>/book-library"
               }
          }

          stage("Acceptance test") {
               steps {
                    sleep 10
                    sh "cucumber"
               }
          }
     }
     post {
          always {
               sh "docker stop book-library"
          }
     }
}